### ISSUE TITLE
ireg

### ISSUE THREAD

**Issue by danielhanlon** [irods/irods_resource_plugin_wos#1571]
Hi,

Not sure if this is the best place to ask this but....

I was hoping to be able to use ireg to register objects that we already have in WOS in iRODS. The WOS compound resource is working fine with the following:

$ ilsresc
demoResc
wos:compound
├── wosArchive:wos
└── wosCache

and on retrieving an OID from WOS I tried to run:

$ ireg -R wosArchive jBi15OFqAyc7TOAZOELWMWMzDGOqKOI4Hg3zJWHJ /rdZone/home/irods/deptFacultyList.txt

but I get the error:

ERROR: Input path must be absolute

I wondered whether I'm just going about this the wrong way or is it something that's just not possible. 

Thanks,

Daniel.

**Comment by danielhanlon** [comment]
(we're currently running irods4.1.2)

**Comment by trel** [comment]
Hi Daniel,

I'm afraid you're going to have to get those files into iRODS by actually moving them - there's no way for iRODS to currently register files that are not on a 'local' file system (mount point).

https://docs.irods.org/master/icommands/user/#ireg

> The file or the directory of files must already exist on the server
> where the resource is located.  The full path must be supplied for
> both the physicalFilePath and the irodsPath.

**Comment by kellerb** [comment]
We have created an issue to add this functionality to iRODS core: https://github.com/irods/irods/issues/2793

**Comment by danielhanlon** [comment]
Thanks!

Daniel.
