### ISSUE TITLE
wosStageToCachePlugin uses incorrect replica to do a size comparison after staging

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods_resource_plugin_wos#1575]

**Comment by danielhanlon** [comment]
Hi Jason,
Could you go in to a bit more detail of what this bug entails please?
Does this also affect a situation where auto_repl=off but msisync_to_archive is used?
Thanks,
Daniel.

**Comment by jasoncoposky** [comment]
The manner in which replicas are created is not important to the trim operation, if one of the replica sizes are invalid this fix is relevant.  This issue is related to which size is used when data is staged from the WOS system to the cache disk.  The size used to determine if data was correctly staged was not necessarily the size of the replica on the WOS but that of the lowest replica number.  In this specific instance the cache replica had a size of 0, which failed the comparison.  The fix was to find the replica that was resident on the WOS system and use that size for the comparison.
